# yamllint disable rule:line-length
# yamllint disable rule:braces

name: Mutation Testing

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Mutation testing with PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.2"

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/composer
          key: composer-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress

      - name: Collect test coverage
        run: |
          vendor/bin/phpunit --coverage-xml=build/logs/coverage-xml --log-junit=build/logs/junit.xml --coverage-clover=build/logs/clover.xml

      - name: Upload test coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v

      - name: Run Infection
        if: github.event_name == 'pull_request'
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          vendor/bin/infection --coverage=build/logs --threads=$(nproc) --show-mutations --no-interaction --only-covered --only-covering-test-cases --skip-initial-tests --git-diff-lines --git-diff-base=origin/$GITHUB_BASE_REF
